version: '3'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: docker/production/nginx.Dockerfile
    restart: always
    depends_on: 
      - app
    ports:
      - "80:80"

  app:
    restart: always
    env_file: docker/production/.env
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
      args:
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    volumes:
      - ./:/app
    depends_on:
      - db
  
  db:
    restart: always
    image: postgres:13.1
    env_file: docker/production/.env
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}

