version: '3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: docker/production/nginx.Dockerfile
    restart: always
    depends_on: 
      - app
    ports:
      - "8000:80"

  app:
    restart: always
    env_file: docker/production/.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - db
  
  db:
    restart: always
    image: postgres:13.1
    env_file: docker/production/.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}